"use client"

import { useEffect, useState } from "react"

export default function DebugLocalStorage() {
  const [localStorageData, setLocalStorageData] = useState({})

  useEffect(() => {
    // Update localStorage data every second
    const interval = setInterval(() => {
      try {
        const stored = JSON.parse(localStorage.getItem('studentPasswords') || '{}')
        setLocalStorageData(stored)
      } catch (error) {
        console.error("Error reading localStorage:", error)
      }
    }, 1000)
    
    return () => clearInterval(interval)
  }, [])
  
  return (
    <div className="fixed bottom-4 right-4 bg-black/80 text-white p-4 rounded-lg max-w-md max-h-64 overflow-auto text-xs z-50">
      <h3 className="font-bold mb-2 text-green-400">🔍 Live localStorage Debug</h3>
      <div className="space-y-2">
        <p>Total students in localStorage: {Object.keys(localStorageData).length}</p>
        {Object.entries(localStorageData).map(([email, data]) => (
          <div key={email} className="border border-gray-600 p-2 rounded">
            <p className="font-semibold">{data.fullName}</p>
            <p className="text-gray-300">Email: {email}</p>
            <p>Password: {data.password ? `${data.password.substring(0, 10)}...` : 'none'}</p>
            <p>Auto Password: {data.autoGeneratedPassword ? `${data.autoGeneratedPassword.substring(0, 10)}...` : 'none'}</p>
            <p className="text-gray-400 text-xs">
              Created: {data.passwordCreatedAt ? new Date(data.passwordCreatedAt).toLocaleDateString() : 'N/A'}
            </p>
          </div>
        ))}
        {Object.keys(localStorageData).length === 0 && (
          <p className="text-yellow-400">No passwords in localStorage</p>
        )}
      </div>
    </div>
  )
}