"use client"

import { useState } from "react"
import { initialStudentsData } from "@/data/studentsData"
import { Dashboard, StudentDetails } from "@/components"

export default function Page() {
  const [studentsData, setStudentsData] = useState(initialStudentsData)
  const [searchTerm, setSearchTerm] = useState("")
  const [timeFilter, setTimeFilter] = useState("daily")



  const generateStudentId = () => {
    if (studentsData.length === 0) return "STU-2025-0001"
    const ids = studentsData.map(s => {
      const match = s.id.match(/STU-\d{4}-(\d+)/)
      return match ? parseInt(match[1]) : 0
    })
    const maxNumber = Math.max(...ids, 0)
    return `STU-2025-${String(maxNumber + 1).padStart(4, '0')}`
  }

  // ⭐ THIS IS WHERE PASSWORDS GET SAVED ⭐
  const handleAddStudent = (studentData) => {


    const newStudent = {
      id: generateStudentId(),
      name: studentData.fullName || "",
      email: studentData.email || "",
      mobile: studentData.mobile || "",
      dob: studentData.dob || "",
      education: studentData.education || "",
      address: studentData.address || "",
      city: studentData.city || "",
      state: studentData.state || "",
      pincode: studentData.pincode || "",
      guardianName: studentData.guardianName || "",
      guardianRelation: studentData.guardianRelation || "",
      guardianMobile: studentData.guardianMobile || "",
      guardianEmail: studentData.guardianEmail || "",
      guardianAddress: studentData.guardianAddress || "",
      guardianCity: studentData.guardianCity || "",
      guardianState: studentData.guardianState || "",
      guardianPincode: studentData.guardianPincode || "",
      status: studentData.status || "Active",
      profilePhoto: studentData.profilePhoto || "",

      // ⭐⭐⭐ CRITICAL - PASSWORDS MUST BE SAVED HERE ⭐⭐⭐
      password: studentData.password || "",
      autoGeneratedPassword: studentData.autoGeneratedPassword || "",
      passwordCreatedAt: studentData.passwordCreatedAt || new Date().toISOString(),
      passwordExpiryDate: studentData.passwordExpiryDate || new Date(new Date().setFullYear(new Date().getFullYear() + 1)).toISOString(),
      // ⭐⭐⭐ END OF PASSWORD FIELDS ⭐⭐⭐

      testsAttempted: 0,
      videosWatched: 0,
      passRate: 0,
      videoTime: "0h 0m",
      createdAt: new Date().toISOString(),
      joinDate: new Date().toISOString().split('T')[0],
      lastActive: null,
      coursesEnrolled: [],
      assignmentsSubmitted: 0,
      attendancePercentage: 0,
      subjects: [
        { name: "Physics", score: 0, passed: 0, failed: 0, passRate: 0, highScore: 0, lowScore: 0, videosWatched: 0, videoCompletion: 0 },
        { name: "Chemistry", score: 0, passed: 0, failed: 0, passRate: 0, highScore: 0, lowScore: 0, videosWatched: 0, videoCompletion: 0 },
        { name: "Zoology", score: 0, passed: 0, failed: 0, passRate: 0, highScore: 0, lowScore: 0, videosWatched: 0, videoCompletion: 0 },
        { name: "Botany", score: 0, passed: 0, failed: 0, passRate: 0, highScore: 0, lowScore: 0, videosWatched: 0, videoCompletion: 0 },
      ]
    }


    // ⭐ THIS SAVES IT TO STATE ⭐
    setStudentsData(prev => {
      const updated = [...prev, newStudent]


      return updated
    })
  }

  const handleDeleteStudent = (studentId) => {
    setStudentsData(studentsData.filter(student => student.id !== studentId))
  }

  const handleUpdateStudent = (studentId, updatedData) => {
    setStudentsData(
      studentsData.map(student =>
        student.id === studentId
          ? {
            ...student,
            ...updatedData,
            password: updatedData.password || student.password,
            autoGeneratedPassword: updatedData.autoGeneratedPassword || student.autoGeneratedPassword,
          }
          : student
      )
    )
  }

  return (
    <div className="min-h-[100dvh] bg-slate-50">
      <div className="space-y-8 p-6">
        <Dashboard
          timeFilter={timeFilter}
          setTimeFilter={setTimeFilter}
          studentsData={studentsData}
        />

        <StudentDetails
          studentsData={studentsData}
          searchTerm={searchTerm}
          setSearchTerm={setSearchTerm}
          // onAddStudent={handleAddStudent} // DISABLED
          onDeleteStudent={handleDeleteStudent}
          onUpdateStudent={handleUpdateStudent}
        />
      </div>
    </div>
  )
}